### ISSUE TITLE
Auto-restart PHP-CGI after crash

### ISSUE THREAD

**Issue by beppe9000** [wnmp/wnmp#107]
Can a checkbox be added to automatically restart php in case of crash? It seems occurring to me pretty often for no apparent reason.

**Comment by x64architecture** [comment]
There probably is an issue with the php build, I'll look into it.

**Comment by beppe9000** [comment]
my environment is windows server 2016 (x64), using only nginx and php because i have an indipendent mysqld instance on the system. I set 5 php instances and they either crash at the same time or are not relaunched. I am testing [EspoCRM ](https://www.espocrm.com/download/) with[ this configuration](https://www.espocrm.com/documentation/administration/nginx-server-configuration/).

**Comment by chang-zhao** [comment]
I experienced the same issue twice yesterday:

PHP silently stops (which may be normal), but then it doesn't restart (though WNMP sees and shows that it's stopped), so I had to restart it by clicking the button "Start".

Please make it start automatically if it stopped on its own.

**Comment by beppe9000** [comment]
my workaround is to set 50 instances in the control panel

**Comment by x64architecture** [comment]
Sorry about this issue it was a regression (was fixed before see #8 but was removed on accident) for the (imo redundant requirement) of the environment variable PHP_FCGI_MAX_REQUESTS.
