### ISSUE TITLE
No disk in the drive error

### ISSUE THREAD

**Issue by SteelTitanium** [wnmp/wnmp#108]
When starting or stopping nginx. I would get a "no disk in drive" error. 
![image](https://user-images.githubusercontent.com/9903201/48595106-61467480-e921-11e8-93e3-a14505223511.png)
After clicking on continue twice it still starts, but having to deal with this each time gets annoying.

**Comment by x64architecture** [comment]
Should be fixed in latest release nginx doesn't like being built as 64-bit on Windows.
