### ISSUE TITLE
Review and renew php.ini

### ISSUE THREAD

**Issue by chang-zhao** [wnmp/wnmp#109]
Thank you for this piece of software! I'm only starting to try it, but I think I like it and will use.

Just noticed that php.ini contains many old values like

 * `iconv.*` settings deprecated in 5.6, without notice that they are deprecated...
 * 16kb of realpath cache while in PHP 7 recommended 4M...

Maybe it's not of this server stack issue, but an issue of that build of PHP... Just wanted you to know. Also it could be interesting to check the values recommended for Windows (such as zend_extension=php_opcache.dll etc.)

https://php.net/manual/en/install.windows.php

**Comment by x64architecture** [comment]
Thanks for reporting the issue it has been fixed in https://github.com/wnmp/wnmp/commit/edd3bdf11db7e57130bdb8c16808983f772d9925.
