### ISSUE TITLE
Adjust GUI restart setting

### ISSUE THREAD

**Issue by chang-zhao** [wnmp/wnmp#111]
1. Restarting PHP goes OK, but restarting NGINX and MariaDB give errors. There should be 1 sec of delay added before giving commands to kill the process and to start it.

Also, I'm not sure about MariaDB, but NGINX has a command for graceful restart:

"nginx -s reload"

This should be used instead of "stop" or process killing.

2. It would be better if the WNMP GUI window would be resizable.

Thanks :).

**Comment by x64architecture** [comment]
I've added it as an enhancement in https://github.com/wnmp/wnmp/commit/a1b882ac9c1e4d9842806f1de77eb95003f73abe.
