### ISSUE TITLE
php without GD

### ISSUE THREAD

**Issue by antzhi** [wnmp/wnmp#113]
Some apllication like 'Grav' need php extension GD

**Comment by chang-zhao** [comment]
@antzhi If you need additional php extensions,
(1) download them (for example, php_gd2.dll) and put it to php/ext in your wnmp directory.
(2) In your php.ini, find and uncomment the string:

;extension=php_gd2.dll

or just add a new string:

extension=php_gd2.dll

**Comment by antzhi** [comment]
thanks

**Comment by antzhi** [comment]
thanks
