### ISSUE TITLE
MariaDB shell does not open if system non-Unicode language is set to Hebrew

### ISSUE THREAD

**Issue by lpinkhard** [wnmp/wnmp#114]
To reproduce:

1. Set system non-Unicode language to Hebrew
2. Open MariaDB shell
3. Receive error:

ERROR 2019 (00000): Can't initialize character set auto (path: compiled_in)

Problem disappears on changing language setting. This happens on a clean install.

**Comment by x64architecture** [comment]
I haven't had a chance to investigate, but I believe this may have been a MariaDB issue so if you are still facing this problem feel free to reopen this issue.
