### ISSUE TITLE
PHP Only Single Thread

### ISSUE THREAD

**Issue by ikennykachun** [wnmp/wnmp#115]
PHP have start up many children process, however, only the first one can be called.
I have to use other program (i.e. php-cgi-spawner) to allow more than 1 PHP thread running.

**Comment by x64architecture** [comment]
Not sure why this would happen, I also don't know your use case. The PHP Wnmp launches is only meant to be used by nginx. I see no difference between php-cgi-spawner and Wnmp's implementation except maybe theirs uses WaitForSingleObject on the php processes. Closing until further information is provided.
