### ISSUE TITLE
can not enable php-pdo extensions for php-fpm

### ISSUE THREAD

**Issue by huangyanxiong01** [wnmp/wnmp#116]
when cli run under mode, the mysql-pdo can loaded:
```
PS F:\Work\rageframe2> php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
hash
iconv
imap
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
Phar
phpdbg_webhelper
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```
but in php-fpm:
```
<?php
phpinfo()
```
can not find mysql-pdo

**Comment by mittus** [comment]
Check your php folder in path:
![image](https://user-images.githubusercontent.com/711179/85256647-dc103380-b464-11ea-9d2d-924152725ba2.png)
![image](https://user-images.githubusercontent.com/711179/85256841-209bcf00-b465-11ea-8cf7-850f5e4461a2.png)
