### ISSUE TITLE
Unhandled exception loading PHP

### ISSUE THREAD

**Issue by theking2** [wnmp/wnmp#118]
Starting PHP yields an unhandled exception:

[Wnmp_ue.zip](https://github.com/wnmp/wnmp/files/4845378/Wnmp_ue.zip)

Probably due to fire-wall issues

**Comment by x64architecture** [comment]
Yes this is a permissions issue you can try to change the PHP port and make sure Wnmp is running as admin. The exception is now handled in #121.
