### ISSUE TITLE
Adding Chinese translations for the WNMP project

### ISSUE THREAD

**Issue by liuqun** [wnmp/wnmp#123]
![image](https://user-images.githubusercontent.com/64795/91679732-b8135180-eb7b-11ea-92dc-d6d45b025765.png)

Currently, some Chinese translations could be found at:
https://github.com/liuqun/wnmp/tree/i18n-chinese-translations

This is still a Work-in-Progress (WIP)...
中文翻译工作正在进行中...

**Comment by x64architecture** [comment]
@liuqun If you are still interested in translating Wnmp, copy the Resource.resx file in the Wnmp.Language project to Resource.zh-??.resx and do the translations then I can include it in a future release.
