### ISSUE TITLE
Connection to an Oracle database

### ISSUE THREAD

**Issue by mendozada** [wnmp/wnmp#125]
Hello, first of all congratulate you for this excellent work.

I would like to check if there is a possibility to make a connection to an Oracle database with php oci8.
Could you tell me how to do the configuration?

Thank you.

**Comment by x64architecture** [comment]
Assuming the oracle database plugin is in the standard PHP distribution (I think it is) you would need to enable it in the php.ini and configure it. I have no knowledge of how to configure the Oracle plugin.
