### ISSUE TITLE
Minimize to Tray Wnmp on close

### ISSUE THREAD

**Issue by julianxhokaxhiu** [wnmp/wnmp#38]
Actually I always close it by mistake. It would be awesome to have this flag also :)

Thanks in advice

**Comment by murraybiscuit** [comment]
Along similar lines - I like it starting up with Windows, but it's always maximised - could it not run in the tray on startup by default rather?

**Comment by paul-norman** [comment]
+1

**Comment by hellao** [comment]
+1
