### ISSUE TITLE
Password when stopping MariaDB

### ISSUE THREAD

**Issue by julianxhokaxhiu** [wnmp/wnmp#39]
Is it possible to turn off this feature? Is it a setting? A cannot really find some documentation for this.

**Comment by Faks** [comment]
it is easy to fix ... had to write custom file based from xamp project ....
@echo off
cd /D %~dp0
echo MariaDB shutdowm ...
TaskKill /F /IM mysqld.exe

if not exist mariadb\data\%computername%.pid GOTO exit
echo Delete %computername%.pid ...
del mariadb\data\%computername%.pid

:exit
