### ISSUE TITLE
MariaDB never starts

### ISSUE THREAD

**Issue by kingdee40** [wnmp/wnmp#42]
MariaDB doesn't start and when I try to open the MariaDB shell I get the following error.

ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost' (10061 "Unknown
 error")

My port 3306 is open and I tried disabling all firewalls.

**Comment by x64architecture** [comment]
I'm going to need more info, as it works for me.

**Comment by x64architecture** [comment]
Closing as no more info was provided.
