### ISSUE TITLE
configuring www.conf

### ISSUE THREAD

**Issue by slifin** [wnmp/wnmp#43]
I'm trying to raise
    request_terminate_timeout
all tutorials on the web say to modify this value inside www.conf but in the wnmp distro of nginx 
this file doesn't appear to be present

Where can we find www.conf?

**Comment by x64architecture** [comment]
@slifin 
www.conf is only found in PHP - FastCGI Process Manager (FPM) which is only supported in BSD, Linux & Unix OS's. PHP on Windows only supports PHP - FastCGI. Maybe you were looking for this option instead: *max_execution_time*

*request_terminate_timeout*
The timeout for serving a single request after which the worker process will be killed. **This option should be used when the 'max_execution_time' ini option does not stop script execution for some reason.** A value of '0' means 'Off'. Available units: s(econds)(default), m(inutes), h(ours), or d(ays). Default value: 0.
http://php.net/manual/en/install.fpm.configuration.php

**Comment by slifin** [comment]
Thank you
