### ISSUE TITLE
PHP Processes crash

### ISSUE THREAD

**Issue by paul-norman** [wnmp/wnmp#45]
Since upgrading from 2.1.3 to 2.1.6 a few days ago I've had the PHP processes constantly drop on me. There's nothing in the PHP log, but the standard error log is littered with phpmyadmin trying to connect:

    2015/02/27 18:49:17 [error] 8036#3716: *9642 no live upstreams while connecting to upstream, client: 127.0.0.1, server: local.development.com, request: "POST /index.php HTTP/1.1", upstream: "fastcgi://php_processes", host: "local.development.com", referrer: "https://local.development.com/phpmyadmin"
    2015/02/27 18:49:18 [error] 8036#3716: *9866 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while connecting to upstream, client: 127.0.0.1, server: local.development.com, request: "POST /index.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9001", host: "local.development.com", referrer: "https://local.development.com/phpmyadmin"

Restarting the PHP processes fixes the issue for a few hours, but it happens regularly. Any ideas as to what could be causing this?

**Comment by x64architecture** [comment]
@paul-norman Do you leave the Wnmp application open the whole time?

**Comment by paul-norman** [comment]
Thanks for the reply! No, I try to keep my taskbar as clean as possible so I close the control panel as soon as I've initialised the processes (just as I did with 2.1.3).

**Comment by x64architecture** [comment]
Should be fixed in the latest release, I think the issue was that the Wnmp Control Panel was being closed and therefore didn't restart the php processes after 2000 requests, so they exited.
