### ISSUE TITLE
2.1.8 seems to break php through nginx (504)

### ISSUE THREAD

**Issue by slifin** [wnmp/wnmp#48]
I'm still trying to debug what's going on but I upgraded from 2.1.7 to the current release 
with my usual process of replace php.ini and nginx.conf with my custom versions 

after upgrade everything returns a 504, it seems php is unresponsive when accessed through nginx, I can invoke it normally via the command line (php) 

I co-worker said his version has said his version at home has broken too, so he's holding off on upgrading

the php script I'm testing against is just 

    <?php 
        die('test');

**Comment by slifin** [comment]
looks like the port for fastcgi_pass has changed from 9000 to 9001, changing that in my custom config has fixed this issue for me

**Comment by x64architecture** [comment]
I should have made a better notice of this though.
