### ISSUE TITLE
Mysqldump

### ISSUE THREAD

**Issue by paul-norman** [wnmp/wnmp#49]
Not an issue per-say, but it would be great if you could bundle mysqldump.exe with MariaDB in future releases - it's really useful!

**Comment by x64architecture** [comment]
I will add it in the next release, thanks for the suggestion. Should I add any other of the tools back? I stripped them out to decrease the file size.

**Comment by paul-norman** [comment]
mysql_upgrade.exe would be very useful too! 

Honestly, I'd prefer MySQL (over MariaDB) just for compatibility with MySQL Workbench and would also favour removing PHPMyAdmin to save space, but I'd imagine that's not a popular move (especially as MySQL WB is ~25Mb so would have to just be linked to).

**Comment by thstarshine** [comment]
+1 for adding mysqldump back.

**Comment by x64architecture** [comment]
Added in 2.1.9 (Now released)

**Comment by paul-norman** [comment]
Just realised that mysql_upgrade relies on mysqlcheck so if you could add that back in too it would make former far more useful, lol!
