### ISSUE TITLE
composer seems broken in current version of PHP 5.6.5

### ISSUE THREAD

**Issue by slifin** [wnmp/wnmp#50]
I'm getting the same symptoms as this guy (dvrcthewrld) using wnmp: 
https://github.com/composer/composer/issues/3604

I think this can be solved by upgrading PHP

**Comment by slifin** [comment]
I solved this locally by dropping in http://windows.php.net/downloads/releases/php-5.6.11-nts-Win32-VC11-x86.zip to the php folder

**Comment by x64architecture** [comment]
Let me know if this is fixed
