### ISSUE TITLE
Exception not caught when www.getwnmp.org cannot be resolved

### ISSUE THREAD

**Issue by ramattos** [wnmp/wnmp#51]
Using WNMP 2.1.7 in an isolated environment (no Internet access).

After I start it, the systray icon loads, however it doesn't show the control panel right away, and after a couple seconds I get an unhandled System.Net.WebException: The remote name could not be resolved: 'www.getwnmp.org'

I added www.getwnmp.com to my hosts file (resolving to 127.0.0.1), then run WNMP again, and .NET Framework throws another System.Net.WebException again: The remote server returned an error: (404) Not Found.

It should be trivial to catch these exceptions.

**Comment by x64architecture** [comment]
In the current git master the exception is caught and handled, this will be in the next release.
