### ISSUE TITLE
CP options not read on reload

### ISSUE THREAD

**Issue by murraybiscuit** [wnmp/wnmp#55]
In CP > File > Wnmp Options

I'm getting a weird error where CP options are being written to Wnmp.ini when I check boxes (Start with windows, Start all apps, Start minimized). But if I close the CP and reopen it, the updated config doesn't reflect in the checkboxes. 
e.g. `startupwithwindows=True` in the config doesn't result in a checked box in the CP UI.

Can you replicate this? I've just updated, so perhaps I need to restart my system...

**Comment by x64architecture** [comment]
The options settings are currently broke they will be fixed asap.

**Comment by duzun** [comment]
I notice that wnmp overwrites `wnmp.ini` on start, thus this issue.
