### ISSUE TITLE
Windows 7 - error when running application

### ISSUE THREAD

**Issue by aussiDavid** [wnmp/wnmp#59]
After the latest update I get this error everytiem I open Wnmp.

![image](https://cloud.githubusercontent.com/assets/5856280/9849201/b5bd8746-5b27-11e5-9c1c-bd5b1a9a4e6b.png)

The text in the console is as follows

      See the end of this message for details on invoking 
      just-in-time (JIT) debugging instead of this dialog box.

      ************** Exception Text **************
      System.ComponentModel.Win32Exception (0x80004005): Access is denied
         at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
         at System.Diagnostics.Process.Start()
         at Wnmp.Forms.Main.FirstRun()
         at Wnmp.Forms.Main.Main_Load(Object sender, EventArgs e)
         at System.Windows.Forms.Form.OnLoad(EventArgs e)
         at System.Windows.Forms.Form.OnCreateControl()
         at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
         at System.Windows.Forms.Control.CreateControl()
         at System.Windows.Forms.Control.WmShowWindow(Message& m)
         at System.Windows.Forms.Control.WndProc(Message& m)
         at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
         at System.Windows.Forms.ContainerControl.WndProc(Message& m)
         at System.Windows.Forms.Form.WmShowWindow(Message& m)
         at System.Windows.Forms.Form.WndProc(Message& m)
         at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
         at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
         at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

      ************** Loaded Assemblies **************
      mscorlib
          Assembly Version: 4.0.0.0
          Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
          CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
      ----------------------------------------
      Wnmp
          Assembly Version: 2.1.9.0
          Win32 Version: 2.1.9.0
          CodeBase: file:///C:/Wnmp/Wnmp.exe
      ----------------------------------------
      System.Windows.Forms
          Assembly Version: 4.0.0.0
          Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR
          CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
      ----------------------------------------
      System.Drawing
          Assembly Version: 4.0.0.0
          Win32 Version: 4.0.30319.34270 built by: FX452RTMGDR
          CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
      ----------------------------------------
      System
          Assembly Version: 4.0.0.0
          Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
          CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
      ----------------------------------------
      System.Configuration
          Assembly Version: 4.0.0.0
          Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
          CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
      ----------------------------------------
      System.Xml
          Assembly Version: 4.0.0.0
          Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
          CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
      ----------------------------------------
      System.Management
          Assembly Version: 4.0.0.0
          Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
          CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
      ----------------------------------------
      System.Core
          Assembly Version: 4.0.0.0
          Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
          CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
      ----------------------------------------

      ************** JIT Debugging **************
      To enable just-in-time (JIT) debugging, the .config file for this
      application or computer (machine.config) must have the
      jitDebugging value set in the system.windows.forms section.
      The application must also be compiled with debugging
      enabled.

      For example:

      <configuration>
          <system.windows.forms jitDebugging="true" />
      </configuration>

      When JIT debugging is enabled, any unhandled exception
      will be sent to the JIT debugger registered on the computer
      rather than be handled by this dialog box.

**Comment by x64architecture** [comment]
Access is denied, move Wnmp to another location or run as admin.
