### ISSUE TITLE
Can't disable cache

### ISSUE THREAD

**Issue by babyChou** [wnmp/wnmp#70]
I'm trying to disable nginx  #cache.
But every time I change my web page content.
 I have to wait  some minutes that changes could reflect on browser.

How could I config my nginx.conf to disabled cache. #

**Comment by x64architecture** [comment]
Remove all of the expires and open_file_cache lines from the conf/nginx.conf file. and/or for [firefox](http://stackoverflow.com/a/26326936/2976394) and for [chrome](http://stackoverflow.com/a/7000899/2976394)
