### ISSUE TITLE
high latency

### ISSUE THREAD

**Issue by ewwink** [wnmp/wnmp#74]
using latest wnmp, anyone know why simple "echo" only use 200ms
`GET http://127.0.0.1:8080/    [HTTP/1.1 200 OK 200ms]`
- wnmp-nginx/1.9.15
- PHP 7.0.6

my nginx before
`GET http://127.0.0.1:8080/ [HTTP/1.1 200 OK 0ms]`
- nginx version: nginx/1.10.1
- PHP 5.6.14

**Comment by x64architecture** [comment]
Probably fixed with ffb96921.
