### ISSUE TITLE
wnmp won't start during relaunch 

### ISSUE THREAD

**Issue by torleif** [wnmp/wnmp#77]
Steps to reproduce:

1. start wnmp
2. launch nginx, db, php
3. close wnmp
4. start wnmp

environment: windows 10

output:
```
Unhandled Exception: System.ArgumentException: String cannot be of zero length.
Parameter name: oldValue
   at System.String.ReplaceInternal(String oldValue, String newValue)
   at System.String.Replace(String oldValue, String newValue)
   at Wnmp.UI.Main.SetCurlCAPath()
   at Wnmp.Program.Main()
```

**Comment by torleif** [comment]
After looking at the function at https://github.com/wnmp/wnmp/blob/b74eb8d882f038828636c14c1e8a327bf3d7d98a/src/Wnmp.UI/Main.cs#L95, it seems that it's trying to replace some text in this part in php.ini:

```
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
;curl.cainfo =
```
a stupid work around is to remove the "curl.cainfo =" parameter, though ideally the function should check to see if there's any text to replace.

**Comment by x64architecture** [comment]
Thank you for reporting the issue, it will be fixed in the next release.
