### ISSUE TITLE
Wnmp does not start with windows. 

### ISSUE THREAD

**Issue by SgtBatten** [wnmp/wnmp#80]
Windows 10 user

Hi, I have been using Wnmp for several months now and no matter what i've tried I have to manually start it each time I boot or reboot the PC.

I have the option ticked to start with windows. I have also tried adding a shortcut to the windows startup folder but neither seems to work.

Every time i do start it i get a UAC message asking if I want to allow this app from an unknown publisher to make changes to my device. Perhaps UAC is stopping it from starting on boot.

Also I have Wnmp set to start minimised to tray. This has an unfortunate side affect as well. I double click the shortcut on my Desktop. the UAC message pops up and i click yes. Wnmp Starts minimised as expected. However, nginx, Maria and php don't start. They start as soon as I click the small tray icon on the right side of the task bar causing the Wnmp Window to appear.

**Comment by ewwink** [comment]
you need to run as administrator, turn off uac and other setting modification, complete guide https://superuser.com/questions/1002262

**Comment by x64architecture** [comment]
I'll look into this CCleaner bypasses UAC after the first run.

**Comment by SgtBatten** [comment]
Thanks I'll take a look
