### ISSUE TITLE
WNMP on system tray and other problems

### ISSUE THREAD

**Issue by mittus** [wnmp/wnmp#81]
1. If WNMP is opend, when I click on icon in system tray, WNMP no reaction and I can't see him, until I select icon on task bar on Windows 10.

2. If I use some versions PHP, I can't use buttons "Configuration" and "Logs", and if I use other data folder with MariaDB, I can't use button "Logs"

3. Tool Host To IP don't understand, if I use url with http://, and tool Get HTTP Headers don't understand, if I use adress without http://

4. Why not menu in system tray where could be start, stop and restart services?

WNMP - the best web server for Windows, becouse it compact and users can use all versions of PHP, nginx and MariaDB. Thank for your product :)

**Comment by x64architecture** [comment]
I addressed point 4 and 2 in the latest release.
