### ISSUE TITLE
Can you release a new version that support php less than 5.6?

### ISSUE THREAD

**Issue by shaoyikai** [wnmp/wnmp#82]
Recently, a lot of people still use php5.6- . Can you make a wamp version that support php less than 5.6 ? Thank you .

**Comment by ewwink** [comment]
I test with php 5.4 it running normally

**Comment by shaoyikai** [comment]
I mean put the php (such as version 5.4) into the Wnmp.exe file as an another wnmp version.

**Comment by x64architecture** [comment]
Wnmp has support for alternative php versions. I'll probably make a faq somewhere as its not very user visible.
