### ISSUE TITLE
关闭不了MariaDB

### ISSUE THREAD

**Issue by muxiaozi** [wnmp/wnmp#87]
Control Panel Version: 4.0.3
2017/7/11 8:03:54 [Wnmp Main] - Wnmp Version: 2.2.5.0
2017/7/11 8:03:54 [Wnmp Main] - Windows Version: Windows 10 Professional
2017/7/11 8:03:54 [Wnmp Main] - CPU: Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
2017/7/11 8:03:54 [Wnmp Main] - CPU Features: SSE, SSE2, SSE3, SSSE3, VT-x, AES, AVX, AVX2

点击关闭按钮
Stop(): 无法打开计算机“DESKTOP-xxx”上的 Wnmp-MariaDB 服务。

点击Restart按钮
2017/7/11 8:17:19 [Wnmp MariaDB] - Stop(): 无法打开计算机“DESKTOP-xxx”上的 Wnmp-MariaDB 服务。
2017/7/11 8:17:19 [Wnmp MariaDB] - Start(): 无法打开计算机“DESKTOP-xxx”上的 Wnmp-MariaDB 服务。

**Comment by x64architecture** [comment]
I don't know what the problem is sorry, I only speak English but I probably wouldn't be able to assist on the issue.
