### ISSUE TITLE
Suggestion For Instead MariaDB with Mysql New Version

### ISSUE THREAD

**Issue by hellao** [wnmp/wnmp#88]
I am a long time wnmp user from China. I love nginx more than apache. so i don't use  XAMPP.
I love nignx design and build method.
I know the MariaDB 10.2 is exactly similar with Mysql5.6.
But time flies, the MariaDB has much branch and less contributor. On the other hand. MySql release 5.7, it support native JSON, virtual column, group replication.
Through my own observation and contemplation over a long time, I believer the MySQL5.7 or MySQL8 is a better and widespread choice.
thanks for considering my suggestion.
Best Regards.

**Comment by hellao** [comment]
如果熟悉目录，可以自己替换。我已经替换成功了，分享出来给需要的朋友。其实非常简单，只是基于我的理解和观察，MySQL的发展的更新未来会大幅超过MariaDB，所以才有此建议。

替换PHP版本

http://windows.php.net/download/
1、从此处下载相应版本即可，注意 x86，x64，NTS和TS（线程安全和非安全版本）
2、注意保留原来的，php.ini文件和相应的扩展dll文件


替换nginx版本
https://nginx.org/en/download.html
下载相应的windows版本。解压后，替换nginx.exe文件即可。


把MariaDB替换成MySQL
https://dev.mysql.com/
1、去这个页面找相应的MySQ版本，注意x86，x64的区别，可以直接下载zip包。GA版本可以用于生产环境。运行以后MySQL的默认密码为空。可以修改。

ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';
2、正常运行只需要bin，share，data目录和 my.ini文件
3、注意保留  data目录和 my.ini文件

**Comment by x64architecture** [comment]
MariaDB plans to implement the features you listed in the not too distant future so we will stick with MariaDB for now.
