### ISSUE TITLE
pecl extension support only upto vc14, why wnmp use vc15?

### ISSUE THREAD

**Issue by owenliang** [wnmp/wnmp#90]
no more ext can be added([redis](http://windows.php.net/downloads/pecl/releases/redis/3.1.3/) for example) , what can i do.

[php officially](https://wiki.php.net/internals/windows/stepbystepbuild) tells:

> PHP officially supports building with Microsoft's Visual C++ compilers. MinGW and other compilers are NOT supported or even known to work. The free Express and Developer editions can also be used. For more information and how to get the compiler see the supported versions. The following VC versions are supported:
> 
> Visual C++ 9.0 (Visual Studio 2008 or Visual C++ 2008) for PHP 5.4.
> Visual C++ 11.0 (Visual Studio 2012) for PHP 5.5 or 5.6.
> Visual C++ 14.0 (Visual Studio 2015) for PHP 7.0+.

> Setup
> 
> If compiling PHP 7.0+:
> Install Visual Studio 2015

**Comment by x64architecture** [comment]
Thank you for reporting the issue, it has been fixed in 3.1.0.

**Comment by owenliang** [comment]
thanks man
