### ISSUE TITLE
Bug with default version of php and systray issue

### ISSUE THREAD

**Issue by mittus** [wnmp/wnmp#92]
About problem with PHP:
I use php 5.6, and don't whan't use default version php, and now have this directory structure: http://prntscr.com/g545ud, but if I whant use Options, I need first time put php.ini on directory "php", and I have sometimes problem with service, when PHP don't wan't start with message about missing php-cgi.exe on the main directory php. I solve this problem when repeat select in Options my php-version. And have problem with path, when can't open php.ini: http://prntscr.com/g54a17

About systray:
Thank you very much for release issue #81, that would be perfect, if you can display status of services on them: http://prntscr.com/g54bwb

**Comment by x64architecture** [comment]
Thanks for reporting the issue, it will be fixed in the next release.
